---

- name: Start openvswitch services
  systemd:
    name: openvswitch
    state: started
  become: yes

# Normally this is created by apex, but the vagrant boxes need
# to connect to it as well, so it needs to be there before we
# vagrant up
- openvswitch_bridge:
    bridge: 'br-admin'
    state: present
  become: yes

- name: Find virtual switch
  shell: "vagrant status vqfx-pfe | grep running"
  args:
    chdir: "{{ working_dir }}/apex"
  ignore_errors: true
  register: pfe_status

- name: Deploy virtual switch using vagrant
  shell: "vagrant up vqfx-pfe"
  args:
    chdir: "{{ working_dir }}/apex"
  ignore_errors: true
  when: pfe_status.rc == 1

- name: Find virtual routing engine
  shell: "vagrant status vqfx | grep running"
  args:
    chdir: "{{ working_dir }}/apex"
  ignore_errors: true
  register: re_status

- name: Deploy virtual routing engine using vagrant
  shell: "vagrant up vqfx"
  args:
    chdir: "{{ working_dir }}/apex"
  ignore_errors: true
  when: re_status.rc == 1

- name: Create expect script for vqfx
  copy:
    src: expect.sh
    dest: "{{ working_dir }}/apex"
  when: re_status.rc == 1

- name: Create wait script for vqfx
  copy:
    src: wait.sh
    dest: /tmp/wait.sh
  when: re_status.rc == 1

- name: Copy wait script into vqfx
  shell: "bash expect.sh"
  args:
    chdir: "{{ working_dir }}/apex"
  when: re_status.rc == 1
