- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    working_dir: "/home/anet-working-dir/apex"
    vagrant_working_dir: "/home/vagrant-working-dir/vagrant"
    apex_repo: "https://github.com/michaeltchapman/apex"
    #clean_vagrant_vms: true
    #clean_apex_vms: true

  # build images, boot virtual switches and deploy apex
  roles:
    - virthost/setup-common
    #- virthost/teardown-vagrant
    #- virthost/teardown-nodepool
    - virthost/setup-vagrant
    - virthost/setup-nodepool
    # start from here if re-using an existing deployment
    - virthost/post-deploy-nodepool

- hosts: undercloud
  roles:
    # If there is no overcloud, redeploy it
    #- undercloud/deploy_overcloud

    # Register overcloud to inventory
    - undercloud/deploy-nodepool
