- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    working_dir: "/home/anet-working-dir"
    apex_repo: "https://github.com/michaeltchapman/apex"
    clean_vagrant_vms: true
    clean_apex_vms: true

  # build images, boot virtual switches and deploy apex
  roles:
    - virthost/setup

  # register the overcloud via the undercloud
- hosts: undercloud 
  roles:
    - undercloud/setup

  # configure overcloud controllers for networking-ansible
- hosts: overcloud_controllers 
  roles:
    - overcloud/setup

  # provision network and configure flavors
- hosts: undercloud
  roles:
    - undercloud/network_flavor
 
  # create new baremetal node
- hosts: localhost 
  connection: local
  roles:
    - virthost/add_ironic_node
 
  # add new baremetal node to overcloud ironic
- hosts: undercloud 
  roles:
    - undercloud/add_ironic_node
 
  # deploy to new baremetal node
- hosts: undercloud 
  roles:
    - undercloud/deploy_ironic_node
