- hosts: localhost                                                              
  connection: local                                                             
  gather_facts: no                                                              
                                                                                
  vars:                                                                         
    working_dir: "/home/michapma/anet-testing-repo"                             
                                                                                
  roles:                                                                        
    - apex-anet  
