- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    working_dir: "/home/anet-working-dir/apex"
    vagrant_working_dir: "/home/vagrant-working-dir/vagrant"
    apex_repo: "https://github.com/michaeltchapman/apex"
    #clean_vagrant_vms: true
    #clean_apex_vms: true

  # build images, boot virtual switches and deploy apex
  roles:
    - virthost/setup-common
    #- virthost/teardown-vagrant
    #- virthost/teardown-apex
    - virthost/setup-vagrant
    - virthost/setup-nodepool
    # start from here if re-using an existing deployment
    - virthost/post-deploy-nodepool

- hosts: undercloud
  roles:
    # If there is no overcloud, redeploy it
    - undercloud/deploy_overcloud

    # Register overcloud to inventory
    - undercloud/setup

  # configure overcloud controllers for networking-ansible
- hosts: overcloud_controllers
  roles:
    - overcloud/setup

  # provision network and configure flavors
- hosts: undercloud
  roles:
    - undercloud/network_flavor

  # create new baremetal node
- hosts: localhost
  connection: local
  roles:
    - virthost/add_ironic_node

  # add new baremetal node to overcloud ironic
- hosts: undercloud
  roles:
    - undercloud/add_ironic_node

  # deploy to new baremetal node
- hosts: undercloud
  roles:
    - undercloud/deploy_ironic_node
