---
# 6 Add a new VM that will be deployed by Ironic
#### do this on the hypervisor
#virsh dumpxml baremetal0 > baremetal3
#• edit baremetal 3, strip out identifiers, change storage, update first nic to attach to the external ovs bridge and the second nic to attach to the switch-appliance
#cp /home/images/baremetal0.qcow2 /home/images/baremetal3.qcow2

# TODO replace with qemu-image create for a blank disk
- name: Copy baremetal image to ironic_bm.qcow2
  command: cp /var/lib/libvirt/images/baremetal0.qcow2 /var/lib/libvirt/images/ironic_bm.qcow2
  become: true

- name: Create ironic_bm definition
  copy:
    src: ironic_bm
    dest: /tmp/ironic_bm
  become: true

- name: check for ironic_vm presence
  shell: virsh list --all | grep ironic_bm
  become: true
  register: ironic_vm_define
  ignore_errors: true

#virsh define baremetal3
- name: Define ironic_bm in libvirt
  command: virsh define /tmp/ironic_bm
  become: true
  when: ironic_vm_define.rc != 0

# needed for port creation later
- name: Get ironic_bm mac address
  shell: virsh domiflist ironic_bm | grep udp | tr -s ' ' '\012' | grep ':'
  become: true
  register: ironic_bm_mac

- name: check for ironic_vbmc presence
  shell: vbmc list | grep ironic_vm
  become: true
  register: ironic_vbmc
  ignore_errors: true

- name: Add ironic_bm to vbmc
  command: vbmc add ironic_bm --port 6232  --username admin --password password --address 192.168.122.1
  become: true
  when: ironic_vbmc.rc != 0

- name: check for ironic_vbmc status
  shell: vbmc list | grep ironic_vm | grep running
  become: true
  register: ironic_vbmc_status
  ignore_errors: true

#vbmc start baremetal3
- name: Start ironic_bm vbmc service
  command: vbmc start ironic_bm
  become: true
  when: ironic_vbmc_status.rc != 0


- name: check for ironic_vbmc iptables port access
  shell: iptables -L | grep 6232
  become: true
  register: ironic_vbmc_iptables
  ignore_errors: true

# allow the vbcm port through the firewall
#iptables -I INPUT -p udp --dport 6232 -j ACCEPT
# https://docs.openstack.org/tripleo-docs/latest/install/environments/virtualbmc.html
- name: Allow vbmc through firewall
  command: iptables -I INPUT -p udp --dport 6232 -j ACCEPT
  become: true
  when: ironic_vbmc_iptables.rc != 0
