---
- name: Deploy virtual switch using vagrant
  shell: "vagrant up vqfx-pfe"
  args:
    chdir: "{{ working_dir }}/apex"
  # Virtual switches do not come up cleanly
  ignore_errors: false

- name: Deploy virtual routing engine using vagrant
  shell: "vagrant up vqfx"
  args:
    chdir: "{{ working_dir }}/apex"
  # Virtual switches do not come up cleanly
  ignore_errors: false
