---
# Normally this is created by apex, but the vagrant boxes need
# to connect to it as well, so it needs to be there before we
# vagrant up
- openvswitch_bridge:
    bridge: 'br-admin'
    state: present

- name: Deploy virtual switch using vagrant
  shell: "vagrant up vqfx-pfe"
  args:
    chdir: "{{ working_dir }}/apex"
  ignore_errors: true

- name: Deploy virtual routing engine using vagrant
  shell: "vagrant up vqfx"
  args:
    chdir: "{{ working_dir }}/apex"
  ignore_errors: true 
