---
# 8. Deploy the ironic node
## Tenant Network configuration

#openstack router create default-router
- name: create router
  shell: source /home/stack/overcloudrc && openstack router create default-router

#openstack router add subnet default-router provisioning-subnet
- name: add provisioning subnet to router
  shell: source /home/stack/overcloudrc && openstack router add subnet default-router provisioning-subnet

#openstack network create --provider-network-type vlan --provider-physical-network tenant tenant-net
- name: create tenant network
  shell: source /home/stack/overcloudrc && openstack network create --provider-network-type vlan --provider-physical-network tenant tenant-net

#openstack subnet create --network tenant-net --subnet-range 192.0.3.0/24     --allocation-pool start=192.0.3.10,end=192.0.3.20 tenant-subnet
- name: create tenant network
  shell: source /home/stack/overcloudrc && openstack subnet create --network tenant-net --subnet-range 192.0.3.0/24     --allocation-pool start=192.0.3.10,end=192.0.3.20 tenant-subnet

#openstack router add subnet default-router tenant-subnet
- name: add tenant subnet to router
  shell: source /home/stack/overcloudrc && openstack router add subnet default-router tenant-subnet

## upload guest kernel, ramdisk and disk images
#openstack image create --public --container-format aki --disk-format aki --file overcloud-full.vmlinuz overcloud-full-vmlinuz
- name: upload guest kernel
  shell: source /home/stack/overcloudrc && openstack image create --public --container-format aki --disk-format aki --file overcloud-full.vmlinuz overcloud-full-vmlinuz

#openstack image create --public --container-format aki --disk-format aki --file overcloud-full.initrd overcloud-full-initrd
- name: upload guest ramdisk
  shell: source /home/stack/overcloudrc && openstack image create --public --container-format aki --disk-format aki --file overcloud-full.initrd overcloud-full-initrd

#openstack image create --file overcloud-full.qcow2 --public --container-format bare --disk-format qcow2 --property kernel_id=`openstack image list |awk '/overcloud-full-vmlinuz/ {print $2}'` --property ramdisk_id=`openstack image list |awk '/overcloud-full-initrd/ {print $2}'` overcloud-full
- name: upload guest image
  shell: source /home/stack/overcloudrc && openstack image create --file overcloud-full.qcow2 --public --container-format bare --disk-format qcow2 --property kernel_id=`openstack image list |awk '/overcloud-full-vmlinuz/ {print $2}'` --property ramdisk_id=`openstack image list |awk '/overcloud-full-initrd/ {print $2}'` overcloud-full

#openstack server create --image overcloud-full --flavor baremetal --nic net-id=$(openstack network show tenant-net -f value -c id) instance1
- name: deploy guest
  shell: source /home/stack/overcloudrc && openstack server create --image overcloud-full --flavor baremetal --nic net-id=$(openstack network show tenant-net -f value -c id) instance1
