# 8. Deploy the ironic node
## Tenant Network configuration
#openstack router create default-router
#openstack router add subnet default-router provisioning-subnet
#openstack network create --provider-network-type vlan --provider-physical-network tenant tenant-net
#openstack subnet create --network tenant-net --subnet-range 192.0.3.0/24     --allocation-pool start=192.0.3.10,end=192.0.3.20 tenant-subnet
#openstack router add subnet default-router tenant-subnet
#
## upload guest kernel, ramdisk and disk images
#openstack image create --public --container-format aki --disk-format aki --file overcloud-full.vmlinuz overcloud-full-vmlinuz
#openstack image create --public --container-format aki --disk-format aki --file overcloud-full.initrd overcloud-full-initrd
#openstack image create --file overcloud-full.qcow2 --public --container-format bare --disk-format qcow2 --property kernel_id=`openstack image list |awk '/overcloud-full-vmlinuz/ {print $2}'` --property ramdisk_id=`openstack image list |awk '/overcloud-full-initrd/ {print $2}'` overcloud-full
#openstack server create --image overcloud-full --flavor baremetal --nic net-id=$(openstack network show tenant-net -f value -c id) instance1 
