---

- name: get overcloud controllers
  shell: source /root/stackrc && nova list | grep controller | cut -d '=' -f 2 | cut -d ' ' -f 1
  register: controller_list

- name: register controllers
  add_host:
    hostname: "{{ item }}"
    ansible_user: heat-admin
    groups: overcloud_controllers
    ansible_ssh_common_args: "-J stack@{{ hostvars['localhost']['undercloud_ip']['stdout'] }}"
    #ansible_ssh_common_args: "-t stack@{{ hostvars['localhost']['undercloud_ip']['stdout'] }}"
  with_items: "{{ controller_list.stdout_lines }}"

- name: copy ssh pub key to undercloud
  copy:
    src: /root/.ssh/id_rsa.pub
    dest: /home/stack/.ssh/id_rsa_virthost.pub
    owner: stack
    group: stack
    mode: 0600

- name: add virthost pubkey to controllers
  shell: "cat /home/stack/.ssh/id_rsa_virthost.pub | ssh -T -i /home/stack/.ssh/id_rsa -o StrictHostKeyChecking=no -o GlobalKnownHostsFile=/dev/null -o UserKnownHostsFile=/dev/null -o LogLevel=error heat-admin@{{ item }} 'cat >> ~/.ssh/authorized_keys'"
  become: true
  with_items: "{{ controller_list.stdout_lines }}"
