---
- name: get nested ip
  shell: "vagrant ssh-config | grep HostName | cut -d ' ' -f 4"
  args:
    chdir: "{{ nested_working_dir }}"
  register: nested_ip
  become: true

- name: get nested identity file
  shell: "vagrant ssh-config | grep IdentityFile"
  args:
    chdir: "{{ nested_working_dir }}"
  register: nested_identity_file
  become: true

- name: add root key to vagrant auth keys
  shell: "ssh-copy-id -f -i /root/.ssh/id_rsa.pub -o '{{ nested_identity_file.stdout }}' -o 'UserKnownHostsFile /dev/null' -o 'StrictHostKeyChecking no' -o 'PasswordAuthentication no' vagrant@{{ nested_ip.stdout }}"
  become: true

- name: add user key to vagrant auth keys
  shell: "ssh-copy-id -f -i /home/{{ ansible_user }}/.ssh/id_rsa.pub -o '{{ nested_identity_file.stdout }}' -o 'UserKnownHostsFile /dev/null' -o 'StrictHostKeyChecking no' -o 'PasswordAuthentication no' vagrant@{{ nested_ip.stdout }}"
  become: true

# register the undercloud as a new node in the inventory
- name: add nested to inventory
  add_host:
    name: nested
    ansible_host: "{{ nested_ip.stdout }}"
    ansible_user: vagrant
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
    groups: nested
