---
- name: Create working directory
  file:
    path: "{{ working_dir }}"
    state: directory
  become: true

- name: Clone apex repo
  git:
    repo: "{{ apex_repo }}"
    dest: "{{ working_dir }}/apex"
    version: "{{ apex_repo_version }}"
  become: true
