---
- name: Search for existing deployment
  shell: virsh list --all | grep subnode | grep running
  register: nodepool_exist
  ignore_errors: true
  become: true

- name: Create nodepool script
  template:
    src: master-repro.sh.j2
    dest: /tmp/master-repro.sh
    owner: oooq
    group: oooq
    mode: "u=rwx,g=rwx,o=r"

- name: Create params file
  template:
    src: params.yaml.j2
    dest: /tmp/repro-params.yaml
    owner: oooq
    group: oooq
    mode: "u=rw,g=rw,o=r"

- name: Run nodepool script
  shell: "/tmp/master-repro.sh -l -e @/tmp/repro-params.yaml"
  when: nodepool_exist.rc != 0
